language: ruby
sudo: false
cache: bundler
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
rvm:
  - 2.3.1
  - 2.4.0
  - 2.5.0
  - 2.6.0
  - jruby-head
  - rbx-2
  - ruby-head
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: ruby-head
